{
    "name": "LIMS Inventory",
    "version": "1.0",
    "category": "Inventory",
    "summary": "Inventory and Asset Management for Laboratories",
    "depends": ["base", "stock", "purchase", "mail", "product", "web"],
    "data": [
        "security/ir.model.access.csv",
        "security/groups_inventory.xml",
        # 'security/access_inventory.xml',
        "data/sequences.xml",
        "views/item_master_data_views.xml",
        "views/vendor_master_data_views.xml",
        "views/purchase_master_data_views.xml",
        "views/grn_master_data_views.xml",
        "views/res_company_views.xml",
        "views/res_config_settings_views.xml",
        # 'views/issue_return_views.xml',
        # 'views/maintenance_calibration_views.xml',
        # 'views/disposal_views.xml',
        # 'views/tracking_views.xml',
        "reports/inventory_reports.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "lims_inventory/static/src/js/custom_script.js",
            # 'lims_inventory/static/src/js/ContractManagement.js',
            #'lims_inventory/static/src/xml/lims_inventory_owl_module.xml',
        ],
    },
    "installable": True,
    "application": True,
    "auto_install": False,
}
